nft_finder/dashboard/models.py
import mongoengine as me
from flask_mongoengine import BaseQuerySet
from PIL import UnidentifiedImageError

BASE_USER_URL = 'https://rarible.com/user/'

class RaribleUser(me.Document):
    _id = me.StringField(required=True) # pk by default
    url = me.URLField()
    avatar_url = me.URLField()
    avatar = me.ImageField(size=(800, 600, True))
    followers = me.IntField(min_value=0, default=0)
    following = me.IntField(min_value=0, default=0)
    page_links = me.ListField(me.URLField())

    owned = me.IntField(min_value=0, default=1)
    sold = me.IntField(min_value=0, default=1)
    created = me.IntField(min_value=0, default=1)

    meta = {'allow_inheritance': True}

    def __repr__(self):
        return f'(Rarible user, id: {self._id})'

    def __str__(self):
        return f'(Rarible user, id: {self._id})'
    
    def clean(self):
        try:
            id_db = RaribleUser.objects.get(_id=self._id)
        except RaribleUser.DoesNotExist:
            id_db = None

        if id_db:
            raise me.ValidationError('Violated unique constrain, the id does already exist in the database.')
        if not self.url:
            self.url = BASE_USER_URL + self._id
        if self.url == BASE_USER_URL:
            raise me.ValidationError("User Id is invalid or has not been submitted.")


class Buyer(RaribleUser):
    owned = me.IntField(min_value=0, default=1)

class Seller(RaribleUser):
    sold = me.IntField(min_value=0, default=1)

class Creator(RaribleUser):
    created = me.IntField(min_value=0, default=1)

class User(me.Document):
    """
    
    -- name: username of a new created user
    -- password: encrypted password of a new user
    -- email: email in from .*@.*\\..*

    """
    name = me.StringField(required=True)
    password = me.StringField(required=True)
    email = me.EmailField(required=True)

    meta = {'queryset_class': BaseQuerySet}

    def clean(self):

        try:
            name_db = User.objects.get(name=self.name)
        except User.DoesNotExist:
            name_db = None

        try:
            email_db = User.objects.get(email=self.email)
        except User.DoesNotExist:
            email_db = None

        if name_db:
            raise me.ValidationError('The username already exists in the database')
        if email_db:
            raise me.ValidationError('The email is already in the system.')

class NftItem(me.Document):
    _id = me.StringField(required=True) # pk by default
    minted_at = me.DateTimeField()
    token_id = me.IntField()
    # time_minted = minted_at - datetime.now
    url = me.URLField()
    name = me.StringField()
    description = me.StringField()
    # picture = me.ImageField(size=(1920, 1080, True))
    filename = me.StringField()
    attr_string = me.StringField()
    # references to participated users
    creators = me.ListField(me.ReferenceField(RaribleUser, reverse_delete_rule=me.CASCADE))
    seller_id = me.ReferenceField(RaribleUser, reverse_delete_rule=me.CASCADE)
    buyer_id = me.ReferenceField(RaribleUser, reverse_delete_rule=me.CASCADE)
    # purchase info
    sold_date = me.DateTimeField(required=True)
    price = me.FloatField(required=True)
    currency = me.StringField(max_length=50, required=True)
    # dict with keys and values for an item
    # attributes = me.DictField(required=True)
    # additional info needed for validation
    # deleted = BooleanField(required=True)

    def __repr__(self):
        return f'(Rarible item, createdAt: {self.minted_at}, id: {self._id})'

    def __str__(self):
        return f'(Rarible item, createdAt: {self.minted_at}, id: {self._id})'

    def clean(self):
        try:
            id_db = NftItem.objects.get(_id=self._id)
        except NftItem.DoesNotExist:
            id_db = None

        if id_db:
            raise me.ValidationError(f'Violated unique constrain, the id {self._id} does already exist in the database.')
        else:
            if self.url:
                try:
                   avatar_img = 1
                except UnidentifiedImageError as err:
                    print(err)
                    avatar_img = None
                if avatar_img:
                    self.filename = avatar_img
                    filename_txt = avatar_img[: 12] + '.txt'
                    with open(filename_txt, 'w') as f:
                        try:
                            f.write(self.attr_string)
                        except UnicodeEncodeError as err:
                            print(err)
                            f.write("Default string")
                    #with open(avatar_img, 'rb') as img:
                    #    self.picture.put(img)
                else:
                    raise me.ValidationError(f'Picture for the item {self._id} could not be loaded.')
        
            #raise me.ValidationError('All submitted nft attributes should be key-value structured.')
        
class ItemAttribute(me.Document):
    """test_string"""
    # id will be automatically set
    item_id = me.ReferenceField(NftItem, required=True) # fk
    key = me.StringField(required=True)
    value = me.StringField(required=True)

    def clean(self):

        for attr in [self.key, self.value]:
            value_raw = str(attr).strip()
            # filter out special characters
            value_alnum = str(v for v in value_raw if v.isalnum())
            value_clean = ''.join(value_alnum.split())
            if len(value_clean) < 3 or value_clean.isnumeric():
                attr = None
            else:
                attr = value_clean

nft_finder/dashboard/__init__.py
# Import flask and template operators
import logging
from flask import Blueprint

logger = logging.getLogger(__name__)

dashboard_bp = Blueprint('dashboard', __name__, url_prefix='/dashboard')

import nft_finder.dashboard.routes

nft_finder/dashboard/routes.py
import os
import time
import json
import glob
import pickle
from flask import render_template, send_from_directory, request, url_for, jsonify, redirect, send_file
from nft_finder import cache
from nft_finder.dashboard import dashboard_bp
from nft_finder.tasks import get_dashboard_data, generate_picture
from config import MEDIA_FOLDER, DALLE_FOLDER, WORKDIR, MEDIA_FOLDER_INIT

openings = 0
@cache.cached(timeout=1000)
@dashboard_bp.route('/config', methods=['GET', 'POST'])
def config_dashboard():
    if request.method == 'GET':
        return render_template('dashboard_start.html', data=json.dumps({}))

    return redirect(url_for('dashboard.routes.config_dashboard'))
     

@dashboard_bp.route('/showpage', methods = ['GET'])
def showpage():

    list_of_files = glob.glob(WORKDIR + '/celery_results/*.dat')
    latest_file = max(list_of_files, key=os.path.getctime)

    objects = []
    with (open(latest_file, "rb")) as openfile:
        while True:
            try:
                objects.append(pickle.load(openfile))
            except EOFError:
                break
    objects = objects[0]

    return render_template(
        'dashboard.html',
        top_pairs = objects.get('top_pairs'),
        generated_pairs = objects.get('generated_pairs'),
        rich_pairs = objects.get('rich_pairs'),
        rich_images_with_info = objects.get('rich_images_with_info')
        )

@dashboard_bp.route('/uploads/<path:filename>')
def download_file(filename):
    try:
        return send_from_directory(MEDIA_FOLDER_INIT, filename, as_attachment=True, cache_timeout = 0)
    except Exception:
        return send_from_directory(MEDIA_FOLDER, filename, as_attachment=True, cache_timeout = 0)

@dashboard_bp.route('/download')
def download_picture():
    list_of_folders = glob.glob(os.path.join(DALLE_FOLDER, 'outputs', '*'))
    latest_folder = max(list_of_folders, key=os.path.getmtime)
    gen_pictures = glob.glob(os.path.join(latest_folder, '*.png'))
    gen_pictures.extend(glob.glob(os.path.join(latest_folder, '*.jpg')))
    gen_pictures.sort(key=os.path.getctime)
    result = gen_pictures[0]
    ext = result.split('.')[-1]
    name = latest_folder.split(os.path.sep)[-1]
    return send_file(
        result,
        mimetype = f"image/{ext.lower()}",
        attachment_filename=f"{name}.{ext}", 
        as_attachment=True
        )

@dashboard_bp.route('/combine-selections')
def combine_selections():
    if request.form.get('selected_items'):
        user_choice = request.form.get('selected_items')
        print(user_choice)
    return True

@dashboard_bp.route('/longtask', methods=['POST'])
def longtask():
   num_items = int(request.args.get('num_items'))
   start_date = request.args.get('start_date')
   end_date = request.args.get('end_date')
   task = get_dashboard_data.delay(num_items, start_date, end_date)
   return jsonify({}), 202, {
       'Location': url_for(
           'dashboard.taskstatus',
           task_id=task.id
           )
       }

@dashboard_bp.route('/picture_longtask', methods=['POST'])
def picture_longtask():
    data = request.args.get('data')
    task = generate_picture.delay(data)
    return jsonify({}), 202, {
       'Location': url_for(
           'dashboard.taskstatus',
           task_id=task.id
           )
       }

@dashboard_bp.route('/status/<task_id>', methods=['GET'])
def taskstatus(task_id):
    task = get_dashboard_data.AsyncResult(task_id)
    if task.state == 'PENDING':
        response = {
            'state': task.state,
            'current': 0,
            'total': 1,
            'status': 'Pending...'
        }
    elif task.state != 'FAILURE':
        response = {
            'state': task.state,
            'current': task.info.get('current', 0),
            'total': task.info.get('total', 1),
            'status': task.info.get('status', '')
        }
        if 'result' in task.info:
            response['result'] = task.info['result']
    else:
        # something went wrong in the background job
        response = {
            'state': task.state,
            'current': 1,
            'total': 1,
            'status': str(task.info),  # this is the exception raised
        }
    return jsonify(response)

nft_finder/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block header %}User Login System{% endblock %}</title>
  {% block navigation %}
  <div class="topnav">
    <span>NFT-Finder</span>
    <a class="active" href="{{ url_for('home') }}">Home</a>
    <a href="{{ url_for('dashboard.config_dashboard') }}">Constructor</a>
  </div>
  {% endblock %}

  <!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  
   -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="{{ url_for('static', filename='normalize.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='footer.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='nav.css') }}">
  <!-- <link rel="stylesheet" href="/static/style.css"> -->
  

  {% block custom_css %}
  {% endblock %}

</head>
<body>

  {% block content %}
  {% endblock %}

  <div class="footer-dark">
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-6 item text">
              <h3>NFT-Finder</h3>
              <p>The website serves to reveal trendy characteristics of NFT Images on the second largest market platform: https://rarible.com</p>
          </div>
          <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="https://www.linkedin.com/in/vladislav-stasenko-999910214/"><i class="icon ion-social-linkedin"></i></a><a href="https://www.instagram.com/vlados2500/"><i class="icon ion-social-instagram"></i></a></div>
          </div>
          <p class="copyright">NFT-Finder © 2022</p>
        </div>
    </footer>
  </div>
  
  <!-- <script src="/static/js/jquery.js"></script>
  <script src="/static/js/scripts.js"></script> -->
  <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

nft_finder/templates/dashboard.html
{% extends "base.html" %}

{% block header %}
    Data Insights
{% endblock %}

{% block navigation %}
  <div class="topnav">
    <span>NFT-Finder</span>
    <a href="{{ url_for('home') }}">Home</a>
    <a class="active" href="{{ url_for('dashboard.config_dashboard') }}">Constructor</a>
  </div>
{% endblock %}

{% block custom_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='showpage.css') }}">
{% endblock %}
{% block content %}
    <section class="page">
        <div class="dshb_user_headings">
            <div class="alert alert-info" role="alert"></div> 
        </div>
        <section>
            <ul class="tabs-controls">
                <li class="tabs-controls__item">
                    <a href="" class="tabs-controls__link tabs-controls__link--active" data-id="1">
                        Total portrait
                    </a>
                </li>
                <li class="tabs-controls__item">
                    <a href="" onclick="" class="tabs-controls__link" data-id="2">
                        Generated Features
                </a>
                </li>
                <li class="tabs-controls__item">
                    <a href="" class="tabs-controls__link" data-id="3">
                        High-price features
                    </a>
                </li>
                <li class="tabs-controls__item">
                    <a href="" class="tabs-controls__link" data-id="4">
                        NFTs
                    </a>
                </li>
            </ul>
        </section>
        <section class="cards-container">
            <div class="card card--current" id="1">
                <h1>Top Pairs (Name and Number of Occurance)</h1>
                <p>
                    <ol>
                    {% for pair in top_pairs %}
                        <li>{{ pair }}</li>
                    {% endfor %}
                    </ol>
                </p>
            </div>
            <div class="card" id="2">
                <h1>Generated Top Pairs (from top keys and top values)</h1>
                <form id="generation_form">
                    <p>
                        <ul style="list-style-type:none;">
                        {% for pair in generated_pairs %}
                            <li><input type="checkbox" id="gen_images_picker" name="selected_items" value="{{ pair }}">{{ pair }}</li>
                        {% endfor %}
                        </ul>
                    </p>
                    <p class="error error--hidden"></p>
                    <button type="submit" class="start-button" id="sendSelectedPairs">Generate</button>
                    <div id="progress"></div>
                    <a href="{{ url_for('dashboard.download_picture') }}" id="redirectButton" class="redirectButton">Download</a> 
                </form>
            </div>
            <div class="card" id="3">
                <h1>Rich Pairs (by sold price)</h1>
                <p>
                    <ol>
                    {% for pair in rich_pairs %}
                        <li>{{ pair }}</li>
                    {% endfor %}
                    </ol>
                </p>
            </div>
            <div class="card" id="4">
                <h1>Most expensive images</h1>
                <p>
                    <ol>
                    {% for i, (img, info) in rich_images_with_info %}
                        <li><img src = "{{ url_for('dashboard.download_file', filename=img) }}" alt= "Image {{ i }}" title = "{{ info }}"/></li>
                    {% endfor %}
                    </ol>
                </p>
            </div>
        </section>
    </section>

    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/nanobar/0.2.1/nanobar.min.js"></script>
    <!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script> -->
    <script type="text/javascript" src="{{ url_for('static', filename='js/flycards.js') }}"></script>
    <script src="{{ url_for('static', filename='js/process_bg_task.js') }}"></script>
    <script>
        $(function() {
            var flashMessageBox = document.getElementsByClassName('alert');
            flashMessageBox[0].innerText = "For image generation, please select any properties in the second tab!";
            flashMessageBox[0].style.display = "block";
        });
    </script>
    <script>
        $('#generation_form').submit(function () {
            get_checkbox_values();
            return false;   
        });
    </script>
    <script>
        function get_checkbox_values() {
            var array = [];
            var checkboxes = document.querySelectorAll('input[type=checkbox]:checked');
            var flashMessageBox = document.getElementsByClassName('alert');
            for (var i = 0; i < checkboxes.length; i++) {
                array.push(checkboxes[i].value);
            }
            if (array.length > 0) {
                flashMessageBox[0].innerText = "Generation is being processed...";
                flashMessageBox[0].style.display = "block";
                start_long_task("/dashboard/picture_longtask", data=array);
            }
        }
    </script>
{% endblock %}

nft_finder/templates/dashboard_start.html
{% extends "base.html" %}

{% block header %}
    Data Insights
{% endblock %}

{% block navigation %}
  <div class="topnav">
    <span>NFT-Finder</span>
    <a href="{{ url_for('home') }}">Home</a>
    <a class="active" href="{{ url_for('dashboard.config_dashboard') }}">Constructor</a>
  </div>
{% endblock %}

{% block custom_css %}
  <link rel="stylesheet" href="/static/start_showpage.css">
{% endblock %}

{% block content %}
    <!--<button onclick="start_long_task();">Start Long Calculation</button><br><br>-->
  <section class="dshb_user_input">
    <div class="dshb_user_headings">
      {% with messages = get_flashed_messages() %}  
          {% if messages %}  
              {% for message in messages %} 
              <div class="alert-message">
                  <p>{{ message }}</p> 
              </div> 
              {% endfor %}  
          {% endif %}  
      {% endwith %}  
    </div>
    <form id="configForm" class="form">
      <div class="title">Welcome</div>
      <div class="subtitle">Please insert number of items:</div>
      <div class="input-container ic1">
        <label for="nb_items">Max 50 entities</label>
        <input id="nb_items" class="input" type="text">
      </div><br>
      <div class="subtitle">Please set date range:</div>
      <div class="input-container ic2">
        <label for="start_date">Start Date</label>
        <input id="start_date" class="input" type="date"><br><br>
        <label for="end_date">End Date</label>
        <input id="end_date" class="input" type="date">
      </div>
      <p class="error error--hidden"></p>
      <button type="submit" class="start-button" id="start-bg-job">Go!</button>
      <div id="progress"></div>
      <a href="{{ url_for('dashboard.showpage') }}" id="redirectButton" class="redirectButton">See result</a> 
    </form>
    
  </section>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/nanobar/0.2.1/nanobar.min.js"></script>
  <script src="{{ url_for('static', filename='js/process_bg_task.js') }}"></script>
  <script>
    $('#configForm').submit(function () {
        var data = {
          numberRequested: document.getElementById("nb_items").value,
          startDate: document.getElementById("start_date").value,
          endDate: document.getElementById("end_date").value
        };
        start_long_task("/dashboard/longtask", data=data);
        return false;
    });
</script>
{% endblock %}

nft_finder/templates/home.html
{% extends "base.html" %}
{% block header %}Home{% endblock %}

{% block content %}
<section class = "home-guide">
    <h1 style="text-align: center; margin-bottom: 50px;">NFT TrendFinder: your guide to the world of digital art.</h1>
    <h3 style="text-align: center;">Who are we and how we can help you?</h3>
    <ul>
        <li style="margin: 50px 0px 50px 600px; line-height: 200%; font-size: large; overflow-wrap: break-word">
            <p>
                We created algorithm that will give you access to the world of art by providing <br>
                up-to-date information about the most popular NFTs, artists and styles. <br>
                It will then provide you with a unique NFT generated based on this information.
            </p>
        </li>
        <li style="margin: 25px 0px 0px 600px; line-height: 200%; font-size: large; overflow-wrap: break-word">
            <p>
                NFT TrendFinder collects characteristics of the most expensive images <br>
                from the NFT marketplace - Rarible in text format, generate a dataset of text pairs <br>
                and passes them to the neural network - DALL-E, so that it produces new works of art. <br>
                Without extra time for market analysis and creating pictures.
            </p>
        </li>
    </ul>
</section>

{% endblock %}